; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.32"

; Modules
projects[addressfield][subdir] = "contrib"
projects[addressfield][version] = "1.0"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.4"

projects[commerce][subdir] = "contrib"
projects[commerce][version] = "1.11"

projects[devel][subdir] = "contrib"
projects[devel][version] = "1.5"

projects[devel_themer][subdir] = "contrib"
projects[devel_themer][version] = "1.x-dev"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.5"

projects[entityform][subdir] = "contrib"
projects[entityform][version] = "2.0-rc1"

projects[features][subdir] = "contrib"
projects[features][version] = "2.2"

projects[fieldable_panels_panes][subdir] = "contrib"
projects[fieldable_panels_panes][version] = "1.5"

projects[i18n][subdir] = "contrib"
projects[i18n][version] = "1.11"

projects[panels][subdir] = "contrib"
projects[panels][version] = "3.4"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "2.5"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.2"

projects[livereload][subdir] = "contrib"
projects[livereload][version] = "2.0"

projects[mobile_navigation][subdir] = "contrib"
projects[mobile_navigation][version] = "1.2"

projects[module_filter][subdir] = "contrib"
projects[module_filter][version] = "2.0-alpha2"

projects[navbar][subdir] = "contrib"
projects[navbar][version] = "1.5"

projects[panelizer][subdir] = "contrib"
projects[panelizer][version] = "3.1"

projects[profiler_builder][subdir] = "contrib"
projects[profiler_builder][version] = "1.2"

projects[rules][subdir] = "contrib"
projects[rules][version] = "2.9"

projects[semantic_panels][subdir] = "contrib"
projects[semantic_panels][version] = "1.2"

projects[simplehtmldom][subdir] = "contrib"
projects[simplehtmldom][version] = "1.12"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[site_config][download][type] = ""
projects[site_config][download][url] = ""
projects[site_config][type] = "module"
projects[site_config][subdir] = "custom"
projects[site_config][version] = "1.0-beta"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0"

projects[token][subdir] = "contrib"
projects[token][version] = "1.6"

projects[ultimate_cron][subdir] = "contrib"
projects[ultimate_cron][version] = "2.0-beta8"

projects[uuid][subdir] = "contrib"
projects[uuid][version] = "1.0-alpha6"

projects[uuid_features][subdir] = "contrib"
projects[uuid_features][version] = "1.0-alpha4"

projects[variable][subdir] = "contrib"
projects[variable][version] = "2.5"

projects[variable_debug][subdir] = "contrib"
projects[variable_debug][version] = "1.1"

projects[views][subdir] = "contrib"
projects[views][version] = "3.8"

projects[webform][subdir] = "contrib"
projects[webform][version] = "4.7"

projects[webform_template][subdir] = "contrib"
projects[webform_template][version] = "4.x-dev"

projects[webform_validation][subdir] = "contrib"
projects[webform_validation][version] = "1.9"

; Themes
projects[bootstrap][version] = "3.0"

projects[ember][version] = "2.0-alpha2"

projects[rubik][version] = "4.2"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ajax_link_example][download][type] = ""
projects[ajax_link_example][download][url] = ""
projects[ajax_link_example][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[cruk_stats][download][type] = ""
projects[cruk_stats][download][url] = ""
projects[cruk_stats][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ctool_ajax_form_popup][download][type] = ""
projects[ctool_ajax_form_popup][download][url] = ""
projects[ctool_ajax_form_popup][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ctool_ajax_login][download][type] = ""
projects[ctool_ajax_login][download][url] = ""
projects[ctool_ajax_login][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[demo_panestyles][download][type] = ""
projects[demo_panestyles][download][url] = ""
projects[demo_panestyles][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[example_styles][download][type] = ""
projects[example_styles][download][url] = ""
projects[example_styles][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[js_sample][download][type] = ""
projects[js_sample][download][url] = ""
projects[js_sample][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[panel_plugin_dev][download][type] = ""
projects[panel_plugin_dev][download][url] = ""
projects[panel_plugin_dev][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ubm_exhibitor_redirect][download][type] = ""
projects[ubm_exhibitor_redirect][download][url] = ""
projects[ubm_exhibitor_redirect][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ubm_live_datebox][download][type] = ""
projects[ubm_live_datebox][download][url] = ""
projects[ubm_live_datebox][type] = "module"

; Themes
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[innova][download][type] = ""
projects[innova][download][url] = ""
projects[innova][type] = "theme"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[backbone][download][type] = ""
libraries[backbone][download][url] = ""
libraries[backbone][directory_name] = "backbone"
libraries[backbone][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.cycle][download][type] = ""
libraries[jquery.cycle][download][url] = ""
libraries[jquery.cycle][directory_name] = "jquery.cycle"
libraries[jquery.cycle][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[modernizr][download][type] = ""
libraries[modernizr][download][url] = ""
libraries[modernizr][directory_name] = "modernizr"
libraries[modernizr][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[owl-carousel][download][type] = ""
libraries[owl-carousel][download][url] = ""
libraries[owl-carousel][directory_name] = "owl-carousel"
libraries[owl-carousel][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[underscore][download][type] = ""
libraries[underscore][download][url] = ""
libraries[underscore][directory_name] = "underscore"
libraries[underscore][type] = "library"

